steps:
  - name: gcr.io/cloud-builders/npm
    args:
      - ci
    id: Install
  - name: gcr.io/cloud-builders/npm
    args:
      - run
      - build
    id: Build
  - name: gcr.io/cloud-builders/gcloud
    env:
      - SRV=$_SRV
    id: Sync
    script: |
      mkdir empty
      gsutil -m rsync -r -d empty gs://mecha-build-artifacts/$SRV
      gsutil -m cp -r srv/* gs://mecha-build-artifacts/$SRV
