steps:
  # If a cache exists, fetch it from Cloud Storage
  - name: gcr.io/cloud-builders/gcloud
    id: Fetch cache
    entrypoint: sh
    args:
      - -c
      - |
        (
          set -e
          gsutil hash -h yarn.lock | grep md5 | tr -s " " | awk '{print $3}' > hashed.yarn-lock
          gsutil -m cp "gs://$_CACHE_BUCKET/$(cat hashed.yarn-lock)" cache.tar.gz 2> /dev/null
          test -f cache.tar.gz
          tar -zxf cache.tar.gz
          echo "Using cache from: gs://$_CACHE_BUCKET/$(cat hashed.yarn-lock)"
        ) || true
  # Install Node dependencies
  - name: $_NODE_IMAGE
    id: Yarn install
    entrypoint: sh
    args:
      - -c
      - |
        test -f cache.tar.gz || yarn install
        yarn build
  # Build the Caddy Docker image
  - name: gcr.io/cloud-builders/docker
    id: Tag and push image
    entrypoint: sh
    args:
      - -c
      - |
        docker build --build-arg CADDY_IMAGE=$_CADDY_IMAGE -t $_APP_IMAGE:$SHORT_SHA .
        docker push $_APP_IMAGE:$SHORT_SHA
  - id: Authorize Cloud Build instance
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - -c
      - |
        gcloud container clusters update $_CLUSTER \
          --zone $_ZONE \
          --enable-master-authorized-networks \
          --master-authorized-networks $(curl -s v4.ipv6test.app)/32,$_HOME_IP/32 \
          --no-user-output-enabled \
          --verbosity error
    waitFor: ["-"]
  - name: gcr.io/cloud-builders/gke-deploy
    id: Deploy to GKE
    args:
      - run
      - --filename=deployment.yaml
      - --image=$_APP_IMAGE:$SHORT_SHA
      - --location=$_ZONE
      - --cluster=$_CLUSTER
  - id: Deauthorize Cloud Build instance
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - -c
      - |
        gcloud container clusters update $_CLUSTER \
          --zone $_ZONE \
          --enable-master-authorized-networks \
          --master-authorized-networks $_HOME_IP/32 \
          --no-user-output-enabled \
          --verbosity error
  # Save the Node cache
  - name: gcr.io/cloud-builders/gcloud
    id: Save cache
    entrypoint: sh
    args:
      - -c
      - |
        (
          set -e
          test ! -f cache.tar.gz
          tar -zcf cache.tar.gz node_modules
          gsutil -m cp cache.tar.gz "gs://$_CACHE_BUCKET/$(cat hashed.yarn-lock)"
        ) || true
    waitFor:
      - Tag and push image