apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipv6test-app
  namespace: default
  labels:
    app: ipv6test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ipv6test-app
  template:
    metadata:
      labels:
        app: ipv6test-app
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      containers:
      - name: ipv6test-app
        image: us-central1-docker.pkg.dev/mechapower/apps/ipv6test:e5b6741
        resources:
          limits:
            memory: 24Mi
          requests:
            cpu: 5m
            memory: 6Mi
        readinessProbe:
          httpGet:
            path: /robots.txt
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /robots.txt
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ipv6test-app
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80": {"name": "ipv6test-app-4azzo6t"}}}'
spec:
  type: ClusterIP
  selector:
    app: ipv6test-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80