name: Build

on:
  push:
    paths-ignore:
      - 'iac/**'
      - 'README.md'

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: us-east-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build
        env:
          ECR_REPO: ${{ secrets.ECR_REPO }}
          FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: ./.github/scripts/build.sh
