name: Deploy

on:
  workflow_dispatch: {}

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: generate-tag
        run: echo "tag=$(date +"%Y%m%d-%H%M%S")" >> $GITHUB_OUTPUT
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          aws-region: us-east-2

      - name: Sync to S3
        run: aws s3 sync ./dist s3://${{ secrets.S3_BUCKET }}
      -
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2