name: Deploy to ECS

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  id-token: write # Allow requesting OIDC JWT token

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute short sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # - name: Test vars
      #   run: echo "${{ vars.IMAGE_REPO }}:${{ env.SHORT_SHA }}"

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          provenance: false
          push: true
          tags: ${{ vars.IMAGE_REPO }}:{{ env.SHORT_SHA }}

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ vars.TASK_DEFINITION_FAMILY }} \
            --query taskDefinition > task-definition.json

      - name: Update task definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: caddy
          image: ${{ vars.IMAGE_REPO }}:${{ env.SHORT_SHA }}

      - name: Update service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: ${{ vars.ECS_SERVICE }}
          cluster: ${{ vars.ECS_CLUSTER }}
          wait-for-service-stability: true