name: Deploy

on:
  workflow_dispatch: {}

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.IAM_ROLE }}
        aws-region: us-east-2

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "22.x"

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Sync to S3
      run: aws s3 sync ./dist s3://${{ vars.S3_BUCKET }} --delete

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Generate tag
      id: generate-tag
      run: echo "tag=$(git rev-parse --short HEAD)-$(date +"%Y%m%d-%H%M%S")" >> $GITHUB_OUTPUT

    - name: Generate version file
      run: echo "${{ steps.generate-tag.outputs.tag }}" > version

    - name: Build and push container
      id: build-docker
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        provenance: false
        push: true
        tags: ${{ vars.ECR_REPO }}:${{ steps.generate-tag.outputs.tag }}

    - name: Publish new version
      run: |
        aws lambda update-function-code \
          --function-name ${{ vars.FUNCTION_NAME }} \
          --image-uri ${{ vars.ECR_REPO }}@${{ steps.build-docker.outputs.digest }}

        VERSION=$(aws lambda publish-version \
          --function-name ${{ vars.FUNCTION_NAME }} \
          --description 'New deployment' \
          --query 'Version' \
          --output text)

        MAX_ATTEMPTS=30
        ATTEMPT=0

        while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            VERSION_STATUS=$(aws lambda get-function-configuration \
                --function-name ${{ vars.FUNCTION_NAME }} \
                --qualifier "$VERSION" \
                --query 'LastUpdateStatus' \
                --output text 2>/dev/null)

            if [ "$VERSION_STATUS" = "Successful" ]; then
                echo "Version $VERSION is ready"
                break
            fi

            if [ "$VERSION_STATUS" = "Failed" ]; then
                echo "Version $VERSION failed to update"
                exit 1
            fi

            echo "Waiting for version $VERSION to be ready (attempt $((ATTEMPT+1))/$MAX_ATTEMPTS)"

            sleep 10

            ((ATTEMPT++))
        done

        if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
            echo "Timeout waiting for version $VERSION to be ready"
            exit 1
        fi

        aws lambda update-alias \
          --function-name ${{ vars.FUNCTION_NAME }} \
          --function-version "$VERSION" \
          --name main
